In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('./fraud.csv')

In [3]:
df.head(10)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0.0,0.0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0.0,0.0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0.0,0.0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0.0,0.0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0.0,0.0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0.0,0.0

In [4]:
df.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83561 entries, 0 to 83560
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            83561 non-null  int64
 1   type            83561 non-null  object
 2   amount          83561 non-null  float64
 3   nameOrig        83561 non-null  object
 4   oldbalanceOrg   83560 non-null  float64
 5   newbalanceOrig  83560 non-null  float64
 6   nameDest        83560 non-null  object
 7   oldbalanceDest  83560 non-null  float64
 8   newbalanceDest  83560 non-null  float64
 9   isFraud         83560 non-null  float64
 10  isFlaggedFraud  83560 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 7.0+ MB

In [6]:
df['step'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     1
newbalanceOrig    1
nameDest          1
oldbalanceDest    1
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [8]:
df.shape

(83561, 11)

In [9]:
df['type'].unique()

array(['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],
      dtype=object)

In [10]:
type=df['type'].value_counts()

In [11]:
transaction=type.index

In [12]:
quantity=type.values

In [13]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.13.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (8.2.2)

In [14]:
import plotly.express as px

In [15]:
px.pie(df, values=quantity,names=transaction,hole=0.3,title="Pie Chart Showing Types of Transaction")

In [16]:
df=df.dropna()

In [17]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
83555,10,CASH_OUT,14895.17,C214279684,51759.0,36863.83,C1298314970,979963.09,994858.25,0.0,0.0
83556,10,PAYMENT,7705.70,C1834114901,96490.0,88784.30,M1214836727,0.00,0.00,0.0,0.0
83557,10,CASH_OUT,319045.01,C1964329082,56471.0,0.00,C699133054,0.00,319045.01,0.0,0.0
83558,10,CASH_IN,249169.96,C1421944154,3481.0,252650.96,C790672270,38177.07,0.00,0.0,0.0
83559,10,CASH_OUT,244279.64,C722886752,29968.0,0.00,C1492538502,25680.00,269959.64,0.0,0.0

In [18]:
df.replace(to_replace=['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],value=[1,4,2,5,3],inplace=True)

In [19]:
type

PAYMENT     33529
CASH_OUT    25156
CASH_IN     16818
TRANSFER     7192
DEBIT         866
Name: type, dtype: int64

In [20]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,1,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0.0,0.0
1,1,1,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0.0,0.0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,1.0,0.0
3,1,2,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,1.0,0.0
4,1,1,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
83555,10,2,14895.17,C214279684,51759.0,36863.83,C1298314970,979963.09,994858.25,0.0,0.0
83556,10,1,7705.70,C1834114901,96490.0,88784.30,M1214836727,0.00,0.00,0.0,0.0
83557,10,2,319045.01,C1964329082,56471.0,0.00,C699133054,0.00,319045.01,0.0,0.0
83558,10,3,249169.96,C1421944154,3481.0,252650.96,C790672270,38177.07,0.00,0.0,0.0
83559,10,2,244279.64,C722886752,29968.0,0.00,C1492538502,25680.00,269959.64,0.0,0.0

In [21]:
df['isFraud']=df['isFraud'].map({0:'NO Fraud',1:'FRAUD'})

In [22]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,1,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,NO Fraud,0.0
1,1,1,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,NO Fraud,0.0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,FRAUD,0.0
3,1,2,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,FRAUD,0.0
4,1,1,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,NO Fraud,0.0
...,...,...,...,...,...,...,...,...,...,...,...
83555,10,2,14895.17,C214279684,51759.0,36863.83,C1298314970,979963.09,994858.25,NO Fraud,0.0
83556,10,1,7705.70,C1834114901,96490.0,88784.30,M1214836727,0.00,0.00,NO Fraud,0.0
83557,10,2,319045.01,C1964329082,56471.0,0.00,C699133054,0.00,319045.01,NO Fraud,0.0
83558,10,3,249169.96,C1421944154,3481.0,252650.96,C790672270,38177.07,0.00,NO Fraud,0.0
83559,10,2,244279.64,C722886752,29968.0,0.00,C1492538502,25680.00,269959.64,NO Fraud,0.0

In [23]:
print("No Frauds:",df['isFraud'].value_counts()[0]/len(df['isFraud'])*100)
print("Frauds:",df['isFraud'].value_counts()[1]/len(df['isFraud'])*100)

No Frauds: 99.86596457635231
Frauds: 0.13403542364767831

In [24]:
x=df[['type','amount','oldbalanceOrg','newbalanceOrig']]

In [25]:
y=df.iloc[:,-2]

In [26]:
y

0        NO Fraud
1        NO Fraud
2           FRAUD
3           FRAUD
4        NO Fraud
           ...
83555    NO Fraud
83556    NO Fraud
83557    NO Fraud
83558    NO Fraud
83559    NO Fraud
Name: isFraud, Length: 83560, dtype: object

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [29]:
model=DecisionTreeClassifier()

In [31]:
model.score(x_train,y_train)

1.0

In [38]:
model.predict([[2,181.00,181.00,0.00]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names

array(['FRAUD'], dtype=object)

In [34]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [35]:
x

       type     amount  oldbalanceOrg  newbalanceOrig
0         1    9839.64       170136.0       160296.36
1         1    1864.28        21249.0        19384.72
2         4     181.00          181.0            0.00
3         2     181.00          181.0            0.00
4         1   11668.14        41554.0        29885.86
...     ...        ...            ...             ...
83555     2   14895.17        51759.0        36863.83
83556     1    7705.70        96490.0        88784.30
83557     2  319045.01        56471.0            0.00
83558     3  249169.96         3481.0       252650.96
83559     2  244279.64        29968.0            0.00

[83560 rows x 4 columns]

In [32]:
y_pred=model.predict(x_test)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9985639061752034